resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/9.yaml

packages:
- .

extra-deps:
  - honeycomb-0.1.0.1
  - hs-opentelemetry-api-0.1.0.0
    # - hs-opentelemetry-exporter-otlp-0.0.1.4
  - hs-opentelemetry-otlp-0.0.1.0
  - hs-opentelemetry-propagator-b3-0.0.1.1
  - hs-opentelemetry-propagator-w3c-0.0.1.3
  - hs-opentelemetry-sdk-0.0.3.6
  - hs-opentelemetry-utils-exceptions-0.2.0.0
  - hs-opentelemetry-vendor-honeycomb-0.0.1.1
  - thread-utils-context-0.3.0.3
  - thread-utils-finalizers-0.1.0.0
  - github: parsonsmatt/hs-opentelemetry
    commit: da04eede49e659fde15ce8382e9294a6d6732930
    subdirs:
      - exporters/otlp
